### ISSUE TITLE
side nav bar has overflow scroll bars

### ISSUE THREAD

**Issue by shankj3** [un-loop/participant-portal#1]
**Describe the bug**
Side nav bar has some funky padding that results in x and y scroll bars 

**To Reproduce**
1. Sign in to the system

**Expected behavior**
No scroll bars for nav bar 

**Screenshots**
![Screen Shot 2020-10-22 at 8 51 07 AM](https://user-images.githubusercontent.com/11891205/96897702-be1f0380-1443-11eb-847c-4f2f4bd5ecc2.png)

**Comment by jebeni777** [comment]
I was able to add overflow: hidden to drawerPaper to fix the scrollbar problem in /main/styles.js

**Comment by shankj3** [comment]
@jebeni777 I don't see an associated PR - also I'm curious as to why this nav bar has extra padding at all. it makes me think that the side nav bar wasn't created correctly, there shouldn't really be an overflow
